name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      # Give execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build APK release
      - name: Build Release APK
        run: ./gradlew assembleRelease

      # Upload APK artifact
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: AYIKS-release-apk
          path: app/build/outputs/apk/release/app-release.apk
