name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Setup JDK 17 (cocok dengan compileOptions project kamu)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      # Pastikan gradlew bisa dieksekusi
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon

      # Upload APK ke artifacts
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AYIKS-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
