name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      # 3. Convert line endings ke LF (untuk sed / bash aman)
      - name: Convert line endings to LF
        run: find . -type f -exec dos2unix {} \; || echo "No files to convert"

      # 4. Grant execute permission untuk gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 5. Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon

      # 6. Upload APK debug ke GitHub Actions Artifacts
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AYIKS-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
